### ISSUE TITLE
TypeDiscoverer.FindTypeByFullName is too slow

### ISSUE THREAD

**Issue by bnordli** [ProCoSys/Bifrost#27]
After profiling the ProCoSys application, the `TypeDiscoverer.FindTypeByFullName` accounts for 3,6% of samples. (It is mostly called by `ReadModelService.InstanceMatching`.)

The reason it is slow is because `TypeFinder.FindTypeByFullName` iterates over all known types and checks their fullname. The result of this lookup should be cached.

**Comment by andersnygaard** [comment]
Fixed by pull request #37
