### ISSUE TITLE
Configure.DiscoverAndConfigure is not SOLID

### ISSUE THREAD

**Issue by bnordli** [ProCoSys/Bifrost#30]
Configure.DiscoverAndConfigure blatantly violates the Single Responsibility Principle by newing up 12 instances of different types and doing everything from setting up default values (where null is supplied) to discovering assemblies, to finally creating a container.

Bootstrapping the container should be refactored out to a separate system.

**Comment by andersnygaard** [comment]
Fixed by pull request #37
