### ISSUE TITLE
Upgrade knockout and jquery

### ISSUE THREAD

**Issue by bnordli** [ProCoSys/Bifrost#41]
Bifrost should run on latest versions of jquery and knockout.
In addition, Bifrost.Web should not list them as NuGet dependencies. (Either, clients should provide compatible versions themselves, or just use the version that is bundled with Bifrost using WebConfiguration.ScriptsToInclude.)

This is one step towards fixing #34. In the end, Bifrost should not include any versions of jquery or knockout, but loading them using requirejs.

**Comment by andersnygaard** [comment]
Resolved with pull request #42
