### ISSUE TITLE
DefaultConvention uses Assembly.GetTypes unnecessarily

### ISSUE THREAD

**Issue by bnordli** [ProCoSys/Bifrost#47]
`DefaultConvention.HasMultipleImplementationInSameNamespace` performs `Assembly.GetTypes.Where(t => t.HasInterface(service))` to retrieve a list of implementing types.

It should instead use `IImplementorFinder`, which already knows about implementing types.

**Comment by andersnygaard** [comment]
Resolved with pull request #48
