### ISSUE TITLE
Exceptions during loading of assemblies are not very friendly

### ISSUE THREAD

**Issue by bnordli** [ProCoSys/Bifrost#59]
During bootstrapping, when an ReflectionTypeLoadException is thrown during enumeration of assemblies (for instance, if the run time version of a references assembly does not match the compile time version), one needs to enter the debugger to see which assembly failed.

The ReflectionTypeLoadException should be caught and rethrown as a more specific exception, with a better message than "See the LoaderExceptions property for more information."

**Comment by andersnygaard** [comment]
Resolved with pull request #60
